config/routes.rb
  resources :projects do 
    resources :service_contracts do
      member do
        get :timelog
      end
    end
  end

  resources :service_contracts do
    member do
      get :timelog
    end
    collection do 
      get 'autocomplete'
      get 'bulk_edit'
      post 'bulk_update'
      get 'context_menu'
    end
  end

app/views/issues/_edit_service_contract.html.erb
<% if User.current.allowed_to?(:view_service_contracts, @project) && @project.has_service_contracts(@issue.tracker)  %>
    <% @issue.build_service_contracts_issue if @issue.service_contracts_issue.blank? %>
    <%= labelled_fields_for :service_contracts_issue, @issue.service_contracts_issue do |a| %>

    <div class="service-contracts-issue">
        <div class="splitcontent">
            <div class="splitcontentleft">
                <p><%= a.select :service_contract_id, @project.open_service_contracts_for_all_ancestor_projects_tracker(@issue.tracker).collect{|x| [x.number, x.id]},{include_blank: true},
                                :onchange => "updateIssueFrom('#{escape_javascript update_issue_form_path(@project, @issue)}', this)" %></p>
                <% if @issue.service_contracts_issue.service_contract_id %>
                <p><%= @issue.service_contracts_issue.service_contract.to_s %></p>
                <% end %>
            </div>
            <div class="splitcontentright">
                <p><%= a.check_box :use_spent_hours, 
                                :class => 'use-spent-hours',
                                :onchange => "updateIssueFrom('#{escape_javascript update_issue_form_path(@project, @issue)}', this)" %></p>
                <% unless @issue.service_contracts_issue.use_spent_hours %>
                    <p><%= a.hours_field :hours, :size => 3, :class => 'hours' %></p>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
<% end %>

app/views/issues/_view_service_contract.html.erb
<% if User.current.allowed_to?(:view_service_contracts, @project) && @issue.service_contracts_issue && @issue.service_contract %> 
<div class="attributes">
<%= issue_fields_rows do |rows|
  rows.left l(:label_service_contract), link_to(@issue.service_contract.number,project_service_contract_path(@issue.project,:id => @issue.service_contracts_issue.service_contract_id))
  rows.right l(:label_service_contract_used), @issue.service_contracts_issue.used_hours
end %>
</div>
<% end %>