config/routes.rb
  resources :projects do 
    resources :service_contracts do
      member do
        get :timelog
      end
    end
  end

  resources :service_contracts do
    member do
      get :timelog
    end
    collection do 
      get 'autocomplete'
      get 'bulk_edit'
      post 'bulk_update'
      get 'context_menu'
    end
  end

app/models/service_contract.rb
class ServiceContract < ActiveRecord::Base
  include Redmine::SafeAttributes

  belongs_to :project
  belongs_to :author, class_name: 'User'
  has_many :service_contracts_issue
  has_many :issues, :through => :service_contracts_issue
  has_and_belongs_to_many :trackers, lambda {order(:position)}

  scope :visible, ->(*args) { where(ServiceContract.visible_condition(args.shift || User.current, *args)).joins(:project) }
  
  scope :sorted, -> { order("#{table_name}.subject ASC") }

  acts_as_searchable columns: ["#{ServiceContract.table_name}.subject", "#{ServiceContract.table_name}.number", "#{ServiceContract.table_name}.error_hours"],
                     date_column: :created_at
  acts_as_customizable
  acts_as_attachable

  validates :project_id, presence: true
  validates :author_id, presence: true
  validates :subject, presence: true

  safe_attributes *%w[number subject from_date to_date default_use_spent_hours is_default closed total_hours warning_hours error_hours custom_field_values custom_fields]
  safe_attributes 'project_id', if: ->(service_contract, _user) { service_contract.new_record? }
  safe_attributes 'tracker_ids'

  def initialize(attributes=nil, *args)
    super

    initialized = (attributes || {}).stringify_keys
    if !initialized.key?('trackers') && !initialized.key?('tracker_ids')
        self.trackers = Tracker.sorted.to_a
    end
  end

  def self.visible_condition(user, options = {})
    Project.allowed_to_condition(user, :view_service_contracts, options)
  end

  def self.css_icon
    'icon icon-user'
  end

  def editable_by?(user)
    editable?(user)
  end


  def visible?(user = nil)
    user ||= User.current
    user.allowed_to?(:view_service_contracts, project, global: true)
  end

  def editable?(user = nil)
    user ||= User.current
    user.allowed_to?(:manage_service_contracts, project, global: true)
  end

  def deletable?(user = nil)
    user ||= User.current
    user.allowed_to?(:manage_service_contracts, project, global: true)
  end

  def attachments_visible?(user = nil)
    visible?(user)
  end

  def attachments_editable?(user = nil)
    editable?(user)
  end

  def attachments_deletable?(user = nil)
    deletable?(user)
  end

  def fixed_hours(exclude_issue_id = 0)
    h = ServiceContractsIssue
    .select("sum(hours) hours")
    .where(service_contract_id: self.id)
    .where(use_spent_hours: false)
    .where.not(issue_id: exclude_issue_id)
    .first
    .attributes['hours']
    if h.nil?
      h = 0
    end
    h.to_f
  end

  def spent_hours(exclude_issue_id = 0)
    h = TimeEntry
    .joins("JOIN #{ServiceContractsIssue.table_name} on #{ServiceContractsIssue.table_name}.issue_id = time_entries.issue_id")
    .select("sum(time_entries.hours) hours")
    .where("#{ServiceContractsIssue.table_name}.service_contract_id = ?", id)
    .where("#{ServiceContractsIssue.table_name}.use_spent_hours = ?", true) 
    .where("#{ServiceContractsIssue.table_name}.issue_id != ?", exclude_issue_id)
    .first
    .attributes['hours']
    if h.nil?
      h = 0
    end
    h.to_f
  end

  def total_used_hours(exclude_issue_id = 0)
    total = 0
    if exclude_issue_id == 0
      total = fixed_hours  + spent_hours
    else
      total = fixed_hours(exclude_issue_id) + spent_hours(exclude_issue_id)
    end
    total
  end

  def total_used_hours_with_current(service_contracts_issue)
    total = 0
    if service_contracts_issue
      total = total_used_hours(service_contracts_issue.issue_id)
      if service_contracts_issue.use_spent_hours
        total += service_contracts_issue.issue.total_spent_hours
      elsif service_contracts_issue.hours
        total += service_contracts_issue.hours
      end
      total
    else
      total = total_used_hours
    end
    total
  end

  def total_issue
    issues.count
  end

  def remain_hours
    total_hours - total_used_hours if total_hours
  end

  def validate_hours_error(service_contracts_issue)
    if error_hours.nil? || (error_hours.to_f) == 0
      true
    else
      used = total_used_hours_with_current(service_contracts_issue)
      if used.to_f > error_hours.to_f
        false
      else
        true
      end
    end
  end

  def validate_hours_warning
    if warning_hours.nil? || (warning_hours.to_f) == 0
      true
    else
      if total_used_hours.to_f > warning_hours.to_f
        false
      else
        true
      end
    end
  end

  def to_s
    s = number.to_s + ' ' + subject.to_s
    if to_date
      s = s + ' (Expired:' + format_date(to_date).to_s + ')'
    end

    s = s + ' Used: ' + format_hours(total_used_hours.to_f)

    if total_hours
      s = s + ' Remain: ' + format_hours(remain_hours.to_f)
    end

  end

  alias_attribute :created_on, :created_at
  alias_attribute :updated_on, :updated_at


end

app/controllers/service_contracts_controller.rb
class ServiceContractsController < ApplicationController

  menu_item :service_contracts

  before_action :authorize_global
  before_action :find_service_contract, only: [:show, :edit, :update, :timelog]
  before_action :find_service_contracts, only: [:context_menu, :bulk_edit, :bulk_update, :destroy]
  before_action :find_project

  helper :trackers
  helper :service_contracts
  helper :custom_fields, :context_menus, :attachments, :issues
  include_query_helpers

  accept_api_auth :index, :show, :create, :update, :destroy

  def index

    retrieve_query(ServiceContractQuery)
    @entity_count = @query.service_contracts.count
    @entity_pages = Paginator.new @entity_count, per_page_option, params['page']
    @entities = @query.service_contracts(offset: @entity_pages.offset, limit: @entity_pages.per_page)

  end

  def show
    retrieve_query(ServiceContractsIssueQuery)
    @query.service_contract = @service_contract

    respond_to do |format|
      format.html { 
        @entity_count = @query.issues.count
        @entity_pages = Paginator.new @entity_count, per_page_option, params['page']    
        @entities = @query.issues(offset: @entity_pages.offset, limit: @entity_pages.per_page)
        render :layout => !request.xhr? 
      }
      format.api
      format.js
      format.pdf {
        @entities = @query.issues(:limit => Setting.issues_export_limit.to_i)
        send_file_headers! :type => 'application/pdf', :filename => 'service_contracts.pdf'
      }
      format.csv {
        @issues = @query.issues(:limit => Setting.issues_export_limit.to_i)
        send_data(query_to_csv(@issues, @query, params[:csv]), :type => 'text/csv; header=present', :filename => 'service_contract_issues.csv')
      }
    end
  end

  def timelog
    retrieve_query(ServiceContractTimelogQuery)
    @query.service_contract = @service_contract

    
    #raise @query.inspect
    respond_to do |format|
      format.html {
        @entity_count = @query.service_contract_timelogs.count
        @entity_pages = Paginator.new @entity_count, per_page_option, params['page']    
        @entities = @query.service_contract_timelogs(offset: @entity_pages.offset, limit: @entity_pages.per_page)
        render :layout => !request.xhr?      
      }
      format.api
      format.js
      format.csv {
        @issues = @query.service_contract_timelogs(:limit => Setting.issues_export_limit.to_i)
        send_data(query_to_csv(@issues, @query, params[:csv]), :type => 'text/csv; header=present', :filename => 'service_contract_timelogs.csv')
      }
    end
  end

  def new
    @service_contract = ServiceContract.new
    @service_contract.project = @project
    @service_contract.safe_attributes = params[:service_contract]
    @trackers = Tracker.sorted.to_a

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @service_contract = ServiceContract.new author: User.current
    @service_contract.project = @project
    @service_contract.safe_attributes = params[:service_contract]
    @service_contract.save_attachments(params[:attachments] || (params[:service_contract] && params[:service_contract][:uploads]))
    @trackers = Tracker.sorted.to_a

    respond_to do |format|
      if @service_contract.save
        format.html do
          flash[:notice] = l(:notice_successful_create)
          redirect_back_or_default service_contract_path(@service_contract)
        end
        format.api { render action: 'show', status: :created, location: service_contract_url(@service_contract) }
        format.js { render template: 'common/close_modal' }
      else
        format.html { render action: 'new' }
        format.api { render_validation_errors(@service_contract) }
        format.js { render action: 'new' }
      end
    end
  end

  def edit
    @service_contract.safe_attributes = params[:service_contract]
    @trackers = Tracker.sorted.to_a
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @service_contract.safe_attributes = params[:service_contract]
    @service_contract.save_attachments(params[:attachments] || (params[:service_contract] && params[:service_contract][:uploads]))

    respond_to do |format|
      if @service_contract.save
        format.html do
          flash[:notice] = l(:notice_successful_update)
          redirect_back_or_default service_contract_path(@service_contract)
        end
        format.api { render_api_ok }
        format.js { render template: 'common/close_modal' }
      else
        format.html { render action: 'edit' }
        format.api { render_validation_errors(@service_contract) }
        format.js { render action: 'edit' }
      end
    end
  end

  def destroy
    @service_contracts.each(&:destroy)

    respond_to do |format|
      format.html do
        flash[:notice] = l(:notice_successful_delete)
        redirect_back_or_default service_contracts_path
      end
      format.api { render_api_ok }
    end
  end

  def bulk_edit
  end

  def bulk_update
    unsaved, saved = [], []
    attributes = parse_params_for_bulk_update(params[:service_contract])
    @service_contracts.each do |entity|
      entity.init_journal(User.current) if entity.respond_to? :init_journal
      entity.safe_attributes = attributes
      if entity.save
        saved << entity
      else
        unsaved << entity
      end
    end
    respond_to do |format|
      format.html do
        if unsaved.blank?
          flash[:notice] = l(:notice_successful_update)
        else
          flash[:error] = unsaved.map{|i| i.errors.full_messages}.flatten.uniq.join(",\n")
        end
        redirect_back_or_default :index
      end
    end
  end

  def context_menu
    if @service_contracts.size == 1
      @service_contract = @service_contracts.first
    end

    can_edit = @service_contracts.detect{|c| !c.editable?}.nil?
    can_delete = @service_contracts.detect{|c| !c.deletable?}.nil?
    @can = {edit: can_edit, delete: can_delete}
    @back = back_url

    @service_contract_ids, @safe_attributes, @selected = [], [], {}
    @service_contracts.each do |e|
      @service_contract_ids << e.id
      @safe_attributes.concat e.safe_attribute_names
      attributes = e.safe_attribute_names - (%w(custom_field_values custom_fields))
      attributes.each do |c|
        column_name = c.to_sym
        if @selected.key? column_name
          @selected[column_name] = nil if @selected[column_name] != e.send(column_name)
        else
          @selected[column_name] = e.send(column_name)
        end
      end
    end

    @safe_attributes.uniq!

    render layout: false
  end

  def autocomplete
  end

  private

  def find_service_contract
    @service_contract = ServiceContract.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_service_contracts
    @service_contracts = ServiceContract.visible.where(id: (params[:id] || params[:ids])).to_a
    @service_contract = @service_contracts.first if @service_contracts.count == 1
    raise ActiveRecord::RecordNotFound if @service_contracts.empty?
    raise Unauthorized unless @service_contracts.all?(&:visible?)

    @projects = @service_contracts.collect(&:project).compact.uniq
    @project = @projects.first if @projects.size == 1
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_project
    @project ||= @service_contract.project if @service_contract
    @project ||= Project.find(params[:project_id]) if params[:project_id].present?
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

app/helpers/service_contracts_helper.rb
module ServiceContractsHelper
    #helper :queries

  def _project_service_contract_path(project, action_name = 'show', *args)
    if action_name == 'show'
      if project
        project_service_contract_path(project, *args)
      else
        service_contract_path(*args)
      end
    else
      if project
        timelog_project_service_contract_path(project, *args)
      else
        timelog_service_contract_path(*args)
      end
    end
  end

  def _project_service_contracts_path(project, *args)
    if project
      project_service_contracts_path(project, *args)
    else
      service_contracts_path(*args)
    end
  end

  def service_contract_column_content(column, item)
    value = column.value_object(item)
    if value.is_a?(Array)
      values = value.collect {|v| service_contract_column_value(column, item, v)}.compact
      safe_join(values, ', ')
    else
      service_contract_column_value(column, item, value)
    end
  end
    
  def service_contract_column_value(column, item, value)
    case column.name
    when :number
      link_to value, service_contract_path(item)
    when :subject
      format_object(value)  
    else
      column_value(column, item, value)
    end
  end

  def find_create_service_contracts_issue(issue)
    if issue
      ServiceContractsIssue.where('issue_id', issue.id).first || ServiceContractsIssue.new(:issue_id => issue.id)
    else
      ServiceContractsIssue.new
    end
  end
end

app/views/service_contracts/_form.html.erb
<%= labelled_form_for([@project, @service_contract], html: { multipart: true, id: 'service_contract_form', class: 'tabular', remote: request.xhr? }) do |f| %>
  <%= error_messages_for @service_contract %>

  <div class="box">
      <% if service_contract.safe_attribute?('project_id') && !@project %>
      <p>
        <%= f.label :project_id, ::ServiceContract.human_attribute_name(:project_id) %>
        <%= f.select :project_id, Project.allowed_to(:manage_service_contracts).collect{|x| [x.name, x.id]}, include_blank: true %>
      </p>
      <% end %>

      <% if service_contract.safe_attribute?('number') %>
      <p>
        <%= f.label :number, ::ServiceContract.human_attribute_name(:number) %>
        <%= f.text_field :number %>
      </p>
      <% end %>

      <% if service_contract.safe_attribute?('subject') %>
      <p>
        <%= f.label :subject, ::ServiceContract.human_attribute_name(:subject) %>
        <%= f.text_field :subject %>
      </p>
      <% end %>
      
      
      <% if service_contract.safe_attribute?('from_date') %>
      <p>
        <%= f.label :from_date, ::ServiceContract.human_attribute_name(:from_date) %>
        <%= f.date_field :from_date %>
      </p>
      <% end %>
      <% if service_contract.safe_attribute?('to_date') %>
      <p>
        <%= f.label :to_date, ::ServiceContract.human_attribute_name(:to_date) %>
        <%= f.date_field :to_date %>
      </p>
      <% end %>
      <% if service_contract.safe_attribute?('default_use_spent_hours') %>
      <p>
        <%= f.label :default_use_spent_hours, ::ServiceContract.human_attribute_name(:default_use_spent_hours) %>
        <%= f.check_box :default_use_spent_hours %>
      </p>
      <% end %>
      <% if service_contract.safe_attribute?('is_default') %>
      <p>
        <%= f.label :is_default, ::ServiceContract.human_attribute_name(:is_default) %>
        <%= f.check_box :is_default %>
      </p>
      <% end %>
      <% if service_contract.safe_attribute?('closed') %>
      <p>
        <%= f.label :closed, ::ServiceContract.human_attribute_name(:closed) %>
        <%= f.check_box :closed %>
      </p>
      <% end %>
      <% if service_contract.safe_attribute?('total_hours') %>
      <p>
        <%= f.label :total_hours, ::ServiceContract.human_attribute_name(:total_hours) %>
        <%= f.text_field :total_hours %>
      </p>
      <% end %>
      <% if service_contract.safe_attribute?('warning_hours') %>
      <p>
        <%= f.label :warning_hours, ::ServiceContract.human_attribute_name(:warning_hours) %>
        <%= f.text_field :warning_hours %>
      </p>
      <% end %>
      <% if service_contract.safe_attribute?('error_hours') %>
      <p>
        <%= f.label :error_hours, ::ServiceContract.human_attribute_name(:error_hours) %>
        <%= f.text_field :error_hours %>
      </p>
      <% end %>
      
      <% custom_field_values = service_contract.visible_custom_field_values %>
      <% custom_field_values.each do |value| %>
      <p>
        <%= custom_field_tag_with_label :service_contract, value %>
      </p>
      <% end %>

      <% unless @trackers.empty? %>
      <fieldset class="box tabular" id="service_contract_trackers"><legend><%= toggle_checkboxes_link('#service_contract_trackers input[type=checkbox]') %><%= l(:label_tracker_plural)%></legend>
      <% @trackers.each do |tracker| %>
        <label class="floating">
          <%= check_box_tag 'service_contract[tracker_ids][]', tracker.id, @service_contract.trackers.to_a.include?(tracker), :id => nil %>
          <%= tracker_name_tag tracker %>
        </label>
      <% end %>
      <%= hidden_field_tag 'service_contract[tracker_ids][]', '' %>
      </fieldset>
      <% end %>

      <p id="attachments_form"><label><%= l(:label_attachment_plural) %></label><%= render :partial => 'attachments/form', :locals => {:container => service_contract} %></p>
  </div>


  <% if !request.xhr? %>
    <p>
      <% if f.object.new_record? %>
        <%= submit_tag l(:button_create), title: l(:button_create), class: "button-positive" %>
      <% else %>
        <%= submit_tag l(:button_update), title: l(:button_update), class: "button-positive" %>
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/service_contracts/_issues_list.html.erb
<%= form_tag({}, data: {cm_url: context_menu_service_contracts_path}) do %>
  <%= hidden_field_tag 'back_url', url_for(params: request.query_parameters), id: nil %>
  <div class="autoscroll">
    <table class="list odd-even entities">
      <thead>
        <tr>
          <th class="checkbox hide-when-print">
            <%= check_box_tag 'check_all', '', false, class: 'toggle-selection',
            title: "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
          </th>
          <% @query.inline_columns.each do |column| %>
            <%= column_header(@query, column) %>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% grouped_query_results(entities, @query) do |entity, group_name, group_count, group_totals| %>
          <% if group_name %>
            <% reset_cycle %>
            <tr class="group open">
              <td colspan="<%= @query.inline_columns.size + 2 %>">
                <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
                <span class="name"><%= group_name %></span>
                <% if group_count %>
                <span class="count"><%= group_count %></span>
                <% end %>
                <span class="totals"><%= group_totals %></span>
                <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                'toggleAllRowGroups(this)', class: 'toggle-all') %>
              </td>
            </tr>
          <% end %>
          <tr id="entity_id_<%= entity.id %>" class="entity <%= cycle('odd', 'even') %> hascontextmenu">
            <td class="checkbox hide-when-print"><%= check_box_tag('ids[]', entity.id, false, id: nil) %></td>
            <% @query.inline_columns.each do |column| %>
              <%= content_tag('td', service_contract_column_content(column, entity), class: column.css_classes) %>
            <% end %>            
          </tr>
          <% @query.block_columns.each do |column| %>
            <% if (text = column_content(column, entity)) && text.present? %>
              <tr class="<%= current_cycle %>">
                <td colspan="<%= @query.inline_columns.size + 1 %>" class="<%= column.css_classes %>">
                  <% if query.block_columns.count > 1 %>
                  <span><%= column.caption %></span>
                  <% end %>
                  <%= text %>
                </td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<%= context_menu %>

app/views/service_contracts/_list.html.erb
<%= form_tag({}, data: {cm_url: context_menu_service_contracts_path}) do %>
  <%= hidden_field_tag 'back_url', url_for(params: request.query_parameters), id: nil %>
  <div class="autoscroll">
    <table class="list odd-even entities">
      <thead>
        <tr>
          <th class="checkbox hide-when-print">
            <%= check_box_tag 'check_all', '', false, class: 'toggle-selection',
            title: "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
          </th>
          <% @query.inline_columns.each do |column| %>
            <%= column_header(@query, column) %>
          <% end %>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% grouped_query_results(entities, @query) do |entity, group_name, group_count, group_totals| %>
          <% if group_name %>
            <% reset_cycle %>
            <tr class="group open">
              <td colspan="<%= @query.inline_columns.size + 2 %>">
                <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
                <span class="name"><%= group_name %></span>
                <% if group_count %>
                <span class="count"><%= group_count %></span>
                <% end %>
                <span class="totals"><%= group_totals %></span>
                <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                'toggleAllRowGroups(this)', class: 'toggle-all') %>
              </td>
            </tr>
          <% end %>
          <tr id="entity_id_<%= entity.id %>" class="entity <%= cycle('odd', 'even') %> hascontextmenu">
            <td class="checkbox hide-when-print"><%= check_box_tag('ids[]', entity.id, false, id: nil) %></td>
            <% @query.inline_columns.each do |column| %>
              <%= content_tag('td', service_contract_column_content(column, entity), class: column.css_classes) %>
            <% end %>
            <td class="buttons">
              <% if entity.editable_by?(User.current) %>
              <%= link_to l(:button_edit), edit_service_contract_path(entity),
                           title: l(:button_edit),
                           class: 'icon-only icon-edit' %>
              <%= link_to l(:button_delete), service_contract_path(entity),
                           data: {confirm: l(:text_are_you_sure)},
                           method: :delete,
                           title: l(:button_delete),
                           class: 'icon-only icon-del' %>
              <% end %>
            </td>
          </tr>
          <% @query.block_columns.each do |column| %>
            <% if (text = column_content(column, entity)) && text.present? %>
              <tr class="<%= current_cycle %>">
                <td colspan="<%= @query.inline_columns.size + 1 %>" class="<%= column.css_classes %>">
                  <% if query.block_columns.count > 1 %>
                  <span><%= column.caption %></span>
                  <% end %>
                  <%= text %>
                </td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<%= context_menu %>

app/views/service_contracts/_sidebar.html.erb
<ul>
  <% if @service_contract && !@service_contract.new_record? %>
    <%= content_tag(:li, link_to(l(:button_edit), edit_polymorphic_path([@project, @service_contract]), title: l(:button_edit), class: 'icon icon-edit button')) %>
  <% end %>
  <% if @service_contract.nil? %>
    <%= content_tag(:li, link_to(l(:button_service_contract_new), new_polymorphic_path([@project, :service_contract]), title: l(:title_service_contract_new), class: 'icon icon-add button button-positive')) %>
  <% end %>
  <%= content_tag(:li, link_to(l(:label_service_contracts), polymorphic_path([@project, :service_contracts], set_filter: '1'), title: l(:label_service_contracts), class: 'icon icon-folder button')) %>
</ul>

app/views/service_contracts/context_menu.html.erb
<ul>
  <% if @service_contract %>
    <li><%= context_menu_link l(:button_edit), edit_service_contract_path(@service_contract), class: 'icon icon-edit', disabled: !@can[:edit] %></li>
  <% end %>
  <% if @safe_attributes.include? 'status' %>
  <li class="folder">
    <a href="#" class="submenu icon icon-issue-status" onclick="return false;"><%= l(:field_status) %></a>
    <ul>
      <% ServiceContract.statuses.keys.each do |status| %>
        <li>
          <%= context_menu_link l("service_contract.statuses.#{status}"), bulk_update_service_contract_path(id: @service_contract_ids, service_contract: { status: status }, back_url: @back), method: :put, selected: (@selected[:status] == status), disabled: !@can[:edit], confirm: l(:text_are_you_sure) %>
        </li>
      <% end %>
    </ul>
  </li>
  <% end %>
  <li><%= context_menu_link l(:button_delete), service_contract_path(id: @service_contract_ids, back_url: @back), method: :delete, data: { confirm: l(:text_are_you_sure) }, class: 'icon icon-del', disabled: !@can[:delete] %></li>

  <%= call_hook(:view_service_contracts_context_menu_end, { service_contract: @service_contract, service_contracts: @service_contracts, can: @can, back: @back, project: @project }) %>
</ul>

app/views/service_contracts/edit.html.erb
<%= title l(:heading_service_contract_edit) %>

<%= render partial: 'form', locals: { service_contract: @service_contract } %>

<% ### PAGE CUSTOMS ########################################################## %>
<% content_for :sidebar do %>
  <%= render partial: 'service_contracts/sidebar' %>
<% end %>

app/views/service_contracts/edit.js.erb
var modal = $("#ajax-modal");
modal.html("<%= j render(template: 'service_contracts/edit', formats: [:html]) %>");
showModal(modal.attr("id"));
var submitButton = {
  text:"<%=j l(:button_update) %>",
  title:"<%=j l(:button_update) %>",
  click: function() {$(this).find('form').submit()},
  'class': 'button-positive'
};
var closeButton = {
  text: "<%=j l(:button_close) %>",
  title: "<%=j l(:button_close) %>",
  click: function() {$(this).dialog('close');},
  'class': 'button'
};
modal.dialog('option', {
  buttons: [closeButton, submitButton]
});

app/views/service_contracts/index.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:manage_service_contracts, @project, global: false) %>
    <%= link_to l(:button_service_contract_new), new_project_service_contract_path, class: 'icon icon-add' %>
  <% end %>
</div>
<h2><%= @query.queried_class.to_s %></h2>

<%= form_tag(_project_service_contracts_path(@project), method: :get, id: 'query_form') do %>
  <%= render partial: 'queries/query_form' %>
<% end %>

<% if @query.valid? %>
  <% if @entities.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render_query_totals(@query) %>
    <%= render partial: 'list', locals: { entities: @entities }%>
    <span class="pagination"><%= pagination_links_full @entity_pages, @entity_count %></span>
  <% end %>
<% end %>

app/views/service_contracts/new.html.erb
<%= title l(:heading_service_contract_new) %>

<%= render partial: 'form', locals: { service_contract: @service_contract } %>

<% ### PAGE CUSTOMS ########################################################## %>
<% content_for :sidebar do %>
  <%= render partial: 'service_contracts/sidebar' %>
<% end %>

app/views/service_contracts/show.html.erb
<%= render partial: 'show' %>

app/views/service_contracts/show.js.erb
var modal = $("#ajax-modal");
modal.html("<%= j render(template: 'service_contracts/show', formats: [:html]) %>");
showModal(modal.attr("id"));
var closeButton = {
  text: "<%=j l(:button_close) %>",
  title: "<%=j l(:button_close) %>",
  click: function() {$(this).dialog('close');},
  'class': 'button'
};
modal.dialog('option', {
  buttons: [closeButton, submitButton]
});

app/views/service_contracts/show.pdf.erb
<%= raw issues_to_pdf(@entities, @project, @query) %>

app/views/service_contracts/timelog.html.erb
<%= render partial: 'show' %>